export const SAMPLE_RESPONSE = {
  requestId: "f6f2e314-122d-4ca9-8e42-4894c948d5d5",
  payload: {
    surveyId: "defaultSurvey",
    questions: [
      {
        id: "Q6", //
        order: 6,
        state: "ANSWERED", //
        options: null,
        info: null,
        parent: null, //
        answerType: "NON_BOOLEAN", //
        choices: [
          {
            text: "Heat Pump / Reverse Cycle / Mini splits",
            value: "heatPump",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:A:TYPE-heatpump",
              unselected: null,
            },
            write: {
              selected: "AP:20:C:1,AP:20:A:TYPE-heatpump",
              unselected: null,
            },
          },
          {
            text: "Fireplace",
            value: "fireplace",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 6,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:A:TYPE-fireplace",
              unselected: null,
            },
            write: {
              selected: "AP:20:C:1,AP:20:A:TYPE-fireplace",
              unselected: null,
            },
          },
          {
            text: "Not Sure",
            value: "notSure",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 7,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:C:1-,AP:20:T:null",
              unselected: null,
            },
            write: {
              selected: "AP:20:C:1,AP:20:T:null,AP:20:A:TYPE-null",
              unselected: null,
            },
          },
          {
            text: "Don't have one",
            value: "none",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 8,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:C:0-1",
              unselected: null,
            },
            write: {
              selected: "AP:20:C:0,AP:20:T:null,AP:20:A:TYPE-null",
              unselected: null,
            },
          },
        ], //
        answers: ["heatPump"], //
        valueSelectionMap: null,
        stateMapper: "AP:20-C",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true, //
        multipleChoiceQuestion: false, //
        multipleWithSubChoiceQuestion: false, //
        numberQuestion: false, //
        textQuestion: false, //
        type: "SINGLE", //
        group: "HEATING", //
        text: "Which type of Central Heating System do you use?", //
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q6b",
        order: 8,
        state: "ANSWERED",
        options: null,
        info: null,
        parent: {
          id: "Q6",
          value: ["heatPump"],
        },
        answerType: "NON_BOOLEAN",
        choices: [
          {
            text: "Electricity",
            value: "electricity",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:T:ELECTRIC",
              unselected: null,
            },
            write: {
              selected: "AP:20:T:ELECTRIC",
              unselected: null,
            },
          },
          {
            text: "Not Sure",
            value: "notSure",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:T:null",
              unselected: null,
            },
            write: {
              selected: "AP:20:T:null",
              unselected: null,
            },
          },
        ],
        answers: ["electricity"],
        valueSelectionMap: null,
        stateMapper: "AP:20-T",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "HEATING",
        text: "What fuel does your Heat Pump use?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q6e",
        order: 11,
        state: "ANSWERED",
        options: null,
        info: null,
        parent: {
          id: "Q6",
          value: ["fireplace"],
        },
        answerType: "NON_BOOLEAN",
        choices: [
          {
            text: "Wood",
            value: "wood",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:T:WOOD",
              unselected: null,
            },
            write: {
              selected: "AP:20:T:WOOD",
              unselected: null,
            },
          },
          {
            text: "Natural Gas",
            value: "naturalGas",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:T:GAS",
              unselected: null,
            },
            write: {
              selected: "AP:20:T:GAS",
              unselected: null,
            },
          },
        ],
        answers: ["naturalGas"],
        valueSelectionMap: null,
        stateMapper: "AP:20-T",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "HEATING",
        text: "What fuel does your Fireplace use?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q6g",
        order: 13,
        state: "UNANSWERED",
        options: null,
        info: null,
        parent: {
          id: "Q6",
          value: ["notSure"],
        },
        answerType: "NON_BOOLEAN",
        choices: [
          {
            text: "0 - 4",
            value: "0-4",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:A:AGE-0_4",
              unselected: null,
            },
            write: {
              selected: "AP:20:A:AGE-0_4",
              unselected: null,
            },
          },
          {
            text: "5 - 9",
            value: "5-9",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:A:AGE-5_9",
              unselected: null,
            },
            write: {
              selected: "AP:20:A:AGE-5_9",
              unselected: null,
            },
          },
          {
            text: "10 - 14",
            value: "10-14",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 3,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:A:AGE-10_14",
              unselected: null,
            },
            write: {
              selected: "AP:20:A:AGE-10_14",
              unselected: null,
            },
          },
          {
            text: "15+",
            value: "15+",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 4,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:A:AGE-15+",
              unselected: null,
            },
            write: {
              selected: "AP:20:A:AGE-15+",
              unselected: null,
            },
          },
          {
            text: "Not Sure",
            value: "notSure",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 5,
            subChoiceValidationType: null,
            read: {
              selected: "AP:20:C:1-",
              unselected: null,
            },
            write: {
              selected: "AP:20:A:AGE-null",
              unselected: null,
            },
          },
        ],
        answers: ["notSure"],
        valueSelectionMap: null,
        stateMapper: "AP:20-A:AGE",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "HEATING",
        text: "How old is your Central Heating System (in years)?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q6h",
        order: 14,
        state: "UNANSWERED",
        options: null,
        info: null,
        parent: {
          id: "Q6",
          value: [
            "heatPump",
            "fireplace",
            "notSure",
          ],
        },
        answerType: "NON_BOOLEAN",
        choices: null,
        answers: ["4"],
        valueSelectionMap: null,
        stateMapper: "AP:20-A:SEER",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: false,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: true,
        textQuestion: false,
        type: "NUMBER",
        group: "HEATING",
        text: "What is the SEER Rating of your Central Heating appliance?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q8",
        order: 16,
        state: "ANSWERED",
        options: null,
        info: null,
        parent: null,
        answerType: "NON_BOOLEAN",
        choices: [
          {
            text: "Heat Pump / Reverse cycle / Mini Splits",
            value: "heatPump",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:52:T:ELECTRIC,AP:52:A:TYPE-heatpump",
              unselected: null,
            },
            write: {
              selected: "AP:52:C:1,AP:52:T:ELECTRIC,AP:52:A:TYPE-heatpump",
              unselected: null,
            },
          },
          {
            text: "Not Sure",
            value: "notSure",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 3,
            subChoiceValidationType: null,
            read: {
              selected: "AP:52:T:ELECTRIC,AP:52:A:TYPE-null",
              unselected: null,
            },
            write: {
              selected: "AP:52:C:1,AP:52:T:ELECTRIC,AP:52:A:TYPE-null",
              unselected: null,
            },
          },
          {
            text: "Don't have one",
            value: "none",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 4,
            subChoiceValidationType: null,
            read: {
              selected: "AP:52:C:0-1",
              unselected: null,
            },
            write: {
              selected: "AP:52:C:0,AP:52:T:null,AP:52:A:TYPE-null",
              unselected: null,
            },
          },
        ],
        answers: ["heatPump"],
        valueSelectionMap: null,
        stateMapper: "AP:52-T,AP:52-A,AP:52-C",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "COOLING",
        text: "Which type of Central Cooling System do you use?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q8a",
        order: 17,
        state: "ANSWERED",
        options: null,
        info: null,
        parent: {
          id: "Q8",
          value: ["heatPump", "notSure"],
        },
        answerType: "NON_BOOLEAN",
        choices: [
          {
            text: "0 - 4",
            value: "0-4",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:52:A:AGE-0_4",
              unselected: null,
            },
            write: {
              selected: "AP:52:A:AGE-0_4",
              unselected: "AP:52:A:AGE-null",
            },
          },
          {
            text: "5 - 9",
            value: "5-9",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:52:A:AGE-5_9",
              unselected: null,
            },
            write: {
              selected: "AP:52:A:AGE-5_9",
              unselected: "AP:52:A:AGE-null",
            },
          },
          {
            text: "10 - 14",
            value: "10-14",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 3,
            subChoiceValidationType: null,
            read: {
              selected: "AP:52:A:AGE-10_14",
              unselected: null,
            },
            write: {
              selected: "AP:52:A:AGE-10_14",
              unselected: "AP:52:A:AGE-null",
            },
          },
          {
            text: "15+",
            value: "15+",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 4,
            subChoiceValidationType: null,
            read: {
              selected: "AP:52:A:AGE-15+",
              unselected: null,
            },
            write: {
              selected: "AP:52:A:AGE-15+",
              unselected: "AP:52:A:AGE-null",
            },
          },
          {
            text: "Not Sure",
            value: "notSure",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 5,
            subChoiceValidationType: null,
            read: {
              selected: "AP:52:A:AGE-null",
              unselected: null,
            },
            write: {
              selected: "AP:52:A:AGE-null",
              unselected: "AP:52:A:AGE-null",
            },
          },
        ],
        answers: ["5-9"],
        valueSelectionMap: null,
        stateMapper: "AP:52-A",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "COOLING",
        text: "How old is your Central Cooling System (in years)?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q8b",
        order: 18,
        state: "UNANSWERED",
        options: null,
        info: null,
        parent: {
          id: "Q8",
          value: ["heatPump", "notSure"],
        },
        answerType: "NON_BOOLEAN",
        choices: null,
        answers: ["5"],
        valueSelectionMap: null,
        stateMapper: "AP:52-A:SEER",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: false,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: true,
        textQuestion: false,
        type: "NUMBER",
        group: "COOLING",
        text: "What is the SEER Rating of your Central Cooling appliance?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q13",
        order: 36,
        state: "ANSWERED",
        options: null,
        info: null,
        parent: null,
        answerType: "BOOLEAN",
        choices: [
          {
            text: "Yes",
            value: "yes",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:16:C:1-",
              unselected: null,
            },
            write: {
              selected: "AP:16:C:1",
              unselected: "AP:16:C:0,AP:16:A:TYPE-null",
            },
          },
          {
            text: "No",
            value: "no",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:16:C:0-1",
              unselected: null,
            },
            write: {
              selected: "AP:16:C:0",
              unselected:
                "AP:16:C:0,AP:16:A:TYPE-null,AP:16:A:DIRECTION-null,AP:101:C:0,AP:73:C:0,AP:102:C:0,AP:99:C:0",
            },
          },
        ],
        answers: ["yes"],
        valueSelectionMap: null,
        stateMapper: "AP:16-C",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "SOLAR",
        text: "Do you have solar panel installed in your home?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q13a",
        order: 37,
        state: "ANSWERED",
        options: null,
        info: null,
        parent: {
          id: "Q13",
          value: ["yes"],
        },
        answerType: "NON_BOOLEAN",
        choices: null,
        answers: ["1.9"],
        valueSelectionMap: null,
        stateMapper: "METADATA-Q13a",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: false,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: true,
        textQuestion: false,
        type: "NUMBER",
        group: "SOLAR",
        text: "What is the size of your solar panel in kW?",
        category: null,
        profileCode: "METADATA",
        subType: null,
      },
      {
        id: "Q16",
        order: 47,
        state: "UNANSWERED",
        options: null,
        info: null,
        parent: null,
        answerType: "BOOLEAN",
        choices: [
          {
            text: "Yes",
            value: "yes",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:2:C:1-",
              unselected: null,
            },
            write: {
              selected: "AP:2:C:1,AP:2:T:null,AP:2:A:TYPE-null",
              unselected: null,
            },
          },
          {
            text: "No",
            value: "no",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:2:C:0-1",
              unselected: null,
            },
            write: {
              selected: "AP:2:C:0,AP:2:T:null,AP:2:A:TYPE-null",
              unselected: null,
            },
          },
        ],
        answers: ["yes"],
        valueSelectionMap: null,
        stateMapper: "AP:2-C",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "PP",
        text: "Do you have a pool?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q16b",
        order: 49,
        state: "UNANSWERED",
        options: null,
        info: null,
        parent: {
          id: "Q16",
          value: ["yes"],
        },
        answerType: "NON_BOOLEAN",
        choices: [
          {
            text: "Yes",
            value: "yes",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:2:A:COVER-yes",
              unselected: null,
            },
            write: {
              selected: "AP:2:A:COVER-yes",
              unselected: "AP:2:A:COVER-null",
            },
          },
          {
            text: "No",
            value: "no",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:2:A:COVER-no",
              unselected: null,
            },
            write: {
              selected: "AP:2:A:COVER-no",
              unselected: null,
            },
          },
        ],
        answers: ["no"],
        valueSelectionMap: null,
        stateMapper: "AP:2-A:COVER",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "PP",
        text: "Is your Pool Covered?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q16d",
        order: 51,
        state: "UNANSWERED",
        options: null,
        info: null,
        parent: {
          id: "Q16",
          value: ["yes"],
        },
        answerType: "NON_BOOLEAN",
        choices: [
          {
            text: "Electric",
            value: "electric",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:56:T:ELECTRIC",
              unselected: null,
            },
            write: {
              selected: "AP:56:C:1,AP:56:T:ELECTRIC",
              unselected: null,
            },
          },
          {
            text: "Natural Gas",
            value: "Natural gas",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:56:T:GAS",
              unselected: null,
            },
            write: {
              selected: "AP:56:C:1,AP:56:T:GAS",
              unselected: null,
            },
          },
          {
            text: "Solar",
            value: "solar",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 3,
            subChoiceValidationType: null,
            read: {
              selected: "AP:56:T:SOLAR",
              unselected: null,
            },
            write: {
              selected: "AP:56:C:1,AP:56:T:SOLAR",
              unselected: null,
            },
          },
          {
            text: "Not Sure",
            value: "notSure",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 4,
            subChoiceValidationType: null,
            read: {
              selected: "AP:56:T:OTHER",
              unselected: null,
            },
            write: {
              selected: "AP:56:C:1,AP:56:T:OTHER",
              unselected: null,
            },
          },
        ],
        answers: ["solar"],
        valueSelectionMap: null,
        stateMapper: "AP:56-C",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "PP",
        text: "What type of a Pool Heater do you have?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q18",
        order: 56,
        state: "ANSWERED",
        options: null,
        info: null,
        parent: null,
        answerType: "BOOLEAN",
        choices: [
          {
            text: "Yes",
            value: "yes",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:18:C:1-",
              unselected: null,
            },
            write: {
              selected: "AP:18:C:1,AP:18:T:ELECTRIC",
              unselected: null,
            },
          },
          {
            text: "No",
            value: "no",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:18:C:0-1",
              unselected: null,
            },
            write: {
              selected: "AP:18:C:0,AP:18:T:null",
              unselected: null,
            },
          },
        ],
        answers: ["yes"],
        valueSelectionMap: null,
        stateMapper: "AP:18-C",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "EV",
        text: "Do you have an Electric Vehicle?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q18a",
        order: 57,
        state: "ANSWERED",
        options: null,
        info: null,
        parent: {
          id: "Q18",
          value: ["yes"],
        },
        answerType: "NON_BOOLEAN",
        choices: [
          {
            text: "Always",
            value: "always",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:18:S:3",
              unselected: null,
            },
            write: {
              selected: "AP:18:S:3",
              unselected: "AP:18:S:null",
            },
          },
          {
            text: "Sometimes",
            value: "sometimes",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:18:S:1",
              unselected: null,
            },
            write: {
              selected: "AP:18:S:1",
              unselected: "AP:18:S:null",
            },
          },
          {
            text: "Never",
            value: "never",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 3,
            subChoiceValidationType: null,
            read: {
              selected: "AP:18:S:0",
              unselected: null,
            },
            write: {
              selected: "AP:18:S:0",
              unselected: "AP:18:S:null",
            },
          },
        ],
        answers: ["always"],
        valueSelectionMap: null,
        stateMapper: "AP:18-S",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "EV",
        text: "Do you charge your EV at home?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
      {
        id: "Q19",
        order: 58,
        state: "UNANSWERED",
        options: null,
        info: null,
        parent: null,
        answerType: "NON_BOOLEAN",
        choices: [
          {
            text: "1",
            value: "one",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 1,
            subChoiceValidationType: null,
            read: {
              selected: "AP:9:C:1-2",
              unselected: null,
            },
            write: {
              selected: "AP:9:C:1",
              unselected: null,
            },
          },
          {
            text: "2",
            value: "two",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 2,
            subChoiceValidationType: null,
            read: {
              selected: "AP:9:C:2-3",
              unselected: null,
            },
            write: {
              selected: "AP:9:C:2",
              unselected: null,
            },
          },
          {
            text: "3 or more",
            value: "threeplus",
            parent: null,
            allowedValues: null,
            allowedValuesMap: null,
            selectionType: null,
            order: 3,
            subChoiceValidationType: null,
            read: {
              selected: "AP:9:C:3-",
              unselected: null,
            },
            write: {
              selected: "AP:9:C:3",
              unselected: null,
            },
          },
        ],
        answers: ["two"],
        valueSelectionMap: null,
        stateMapper: "AP:9-C",
        mandatory: false,
        feMultiplierForNumberTypeQuestion: null,
        questionTemplate: null,
        singleChoiceQuestion: true,
        multipleChoiceQuestion: false,
        multipleWithSubChoiceQuestion: false,
        numberQuestion: false,
        textQuestion: false,
        type: "SINGLE",
        group: "REFRIGERATOR",
        text: "How many refrigerators and freezers do you have in your home?",
        category: null,
        profileCode: "AP",
        subType: null,
      },
    ],
  },
  error: null,
};
