export const SCENE_CONFIGS = {
  RESI: {
    USER_TYPE: "RESI",
    SCENE_BASE_OBJECTS: [
      {
        MODEL_NAME: "Base-House",
        MODEL_PATH: "/heavy-assets/models/House.glb",
        POSITION: [0, 0, 0],
        ROTATION: [0, 0, 0],
        SCALE: [0.60, 0.60, 0.60],
        TEXT_POSITION: [],
        COUNT: 1,
      },
    ],
    SCENE_OBJECTS: [
      {
        MODEL_NAME: "EV",
        APPLIANCE_ID: "EV",
        MODEL_PATH: "/heavy-assets/models/EV.glb",
        POSITION: [0, 0, 0],
        ROTATION: [0, 0, 0],
        SCALE: [0.6, 0.6, 0.6],
        TEXT_POSITION: [3.75, 2, -1],
        COUNT: 1,
      },
      {
        MODEL_NAME: "Fireplace",
        APPLIANCE_ID: "HEATING_FIREPLACE",
        MODEL_PATH: "/heavy-assets/models/Fireplace.glb",
        POSITION: [0, 0, 0],
        ROTATION: [0, 0, 0],
        SCALE: [0.6, 0.6, 0.6],
        TEXT_POSITION: [-10, -5, -5],
        COUNT: 1,
      },
      {
        MODEL_NAME: "HeatPump_Gas",
        APPLIANCE_ID: "HEATPUMP_GAS",
        MODEL_PATH: "/heavy-assets/models/HeatPump_Gas.glb",
        POSITION: [0, 0, 0],
        ROTATION: [0, 0, 0],
        SCALE: [0.6, 0.6, 0.6],
        TEXT_POSITION: [7, 0, 7],
        COUNT: 1,
      },
      {
        MODEL_NAME: "Horizon",
        APPLIANCE_ID: "HORIZON",
        MODEL_PATH: "/heavy-assets/models/Horizon.glb",
        POSITION: [0, 0, 0],
        ROTATION: [0, 0, 0],
        SCALE: [0.6, 0.6, 0.6],
        TEXT_POSITION: [-7, -7, 30],
        COUNT: 1,
      },
      {
        MODEL_NAME: "HP_Electric",
        APPLIANCE_ID: "HEATPUMP_ELECTRIC",
        MODEL_PATH: "/heavy-assets/models/HP_Electric.glb",
        POSITION: [1.3, 0, 1],
        ROTATION: [0, 1.6, 0],
        SCALE: [0.2, 0.2, 0.2],
        TEXT_POSITION: [7, -14, -2],
        COUNT: 1,
      },
      {
        MODEL_NAME: "PoolPump",
        APPLIANCE_ID: "POOL_PUMP",
        MODEL_PATH: "/heavy-assets/models/PoolPump.glb",
        POSITION: [-0.2,0,-1],
        ROTATION: [0, 0, 0],
        SCALE: [0.6, 0.6, 0.6],
        TEXT_POSITION: [-7, -7, 6],
      },
      {
        MODEL_NAME: "Refrigerator",
        APPLIANCE_ID: "REFRIGERATOR",
        MODEL_PATH: "/heavy-assets/models/Refrigerator.glb",
        POSITION: [0.3, 0, 0],
        ROTATION: [0, 0, 0],
        SCALE: [0.7, 0.7, 0.7],
        TEXT_POSITION: [-3, 1, 1.20],
        COUNT: 1,
      },
      {
        MODEL_NAME: "Solar",
        APPLIANCE_ID: "SOLAR",
        MODEL_PATH: "/heavy-assets/models/Solar.glb",
        POSITION: [0, 0.4, 0],
        ROTATION: [0, 0, 0],
        SCALE: [0.5, 0.5, 0.5],
        TEXT_POSITION: [0, 4, 0],
        COUNT: 1,
      },
      {
        MODEL_NAME: "Garage",
        APPLIANCE_ID: "GARAGE",
        MODEL_PATH: "/heavy-assets/models/Garage.glb",
        POSITION: [0.25, -0.05,0 ],
        ROTATION: [0, 0, 0],
        SCALE: [0.5, 0.5, 0.5],
        TEXT_POSITION: [0, 10, 0],
      }
    ],
  },
  SMB: {
    USER_TYPE: "SMB",
    SCENE_BASE_OBJECTS: [
      {
        MODEL_NAME: "Base-Fox",
        MODEL_PATH: "/heavy-assets/models/Fox.glb",
        POSITION: [1, 0, 1],
        ROTATION: [0, 3 * Math.PI / 4, 0],
        SCALE: [0.02, 0.02, 0.02],
      },
      {
        MODEL_NAME: "Base-Lantern2",
        MODEL_PATH: "/heavy-assets/models/Lantern2.glb",
        POSITION: [-2, 0, 2.5],
        ROTATION: [0, 1.8 * Math.PI, 0],
        SCALE: [0.1, 0.1, 0.1],
      },
      {
        MODEL_NAME: "Base-Wall",
        MODEL_PATH: "/heavy-assets/models/Wall.gltf",
        POSITION: [3.5 , 0, -2],
        ROTATION: [0, (3 * Math.PI) / 4, 0],
        SCALE: [0.6, 0.6, 0.6],
      },
    ],
    SCENE_OBJECTS: [
      {
        MODEL_NAME: "Scene-House",
        APPLIANCE_ID: "HOUSE",
        MODEL_PATH: "/heavy-assets/models/House.glb",
        POSITION: [0, 0, 0],
        ROTATION: [0, 0, 0],
        SCALE: [1, 1, 1],
      },
      {
        MODEL_NAME: "Scene-Lantern",
        APPLIANCE_ID: "LANTERN",
        MODEL_PATH: "/heavy-assets/models/Lantern.glb",
        POSITION: [2, 0, -1.5],
        ROTATION: [0, (- Math.PI) / 4, 0],
        SCALE: [0.1, 0.1, 0.1],
      },
    ],
  },
  LMI: {
    USER_TYPE: "LMI",
    SCENE_OBJECTS: null,
  },
  EV: {
    USER_TYPE: "EV",
    SCENE_OBJECTS: null,
  },
};